spring:
    application:
        name: square-service
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
server:
    port: 8103

logging:
    charset:
        console: utf-8
